### ISSUE TITLE
Tidy up namespace references in GENEActivReader

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIRread#13]
In [GENEActivReader.csv](https://github.com/wadpac/GGIRread/blob/main/src/GENEActivReader.cpp) I added:

```
using namespace std;
using namespace Rcpp;
```

To do:
Remove these declarations and add explicit namespace reference to every location where they are used, just like how Patrick did it in the rest of the function.

**Comment by egpbos** [comment]
The other option which is also considered good practice is to explicitly define at the top all the names you want to use from the specific namespaces. For instance:

```
using std::string;
using std::stoi;
using Rcpp::List;
using Rcpp::Named;
// etc
```

Then you can use them in the rest of the code without the namespace prefixes and you are still explicit about which ones you use in case of namespace clashes.
